# Generated by Django 4.0.5 on 2022-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=500, unique=True)),
                ('cell1', models.IntegerField(default=0)),
                ('cell2', models.IntegerField(default=0)),
                ('cell3', models.IntegerField(default=0)),
                ('cell4', models.IntegerField(default=0)),
                ('cell5', models.IntegerField(default=0)),
                ('cell6', models.IntegerField(default=0)),
                ('cell7', models.IntegerField(default=0)),
                ('cell8', models.IntegerField(default=0)),
                ('cell9', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'Game state',
                'verbose_name_plural': 'Game states by sessions',
                'ordering': ('-created',),
            },
        ),
    ]
